# Define some variables
@host = ""
@user = ""
@password = ""
@topic = ""

### General

POST https://{{ host }}/general
Content-Type: application/json
X-USER: {{ user }}
X-PASS: {{ password }}
X-TOPIC: {{ topic }}

{
	"subject": "This is the subject",
	"body": "HTML body of the email",
	"receivers": ["email@example.com"]
}

### Check IP
POST https://{{ host }}/check-ip
Content-Type: application/json
X-USER: {{ user }}
X-PASS: {{ password }}
X-TOPIC: {{ topic }}

{
	"new_ip": "192.168.1.1"
}



### Error Message
POST https://{{ host }}/error
Content-Type: application/json
X-USER: {{ user }}
X-PASS: {{ password }}
X-TOPIC: {{ topic }}

{
	"subject": "This is the subject",
	"error_message": "This is the error message"
}


### Saturated Storage
POST https://{{ host }}/saturated-storage
Content-Type: application/json
X-USER: {{ user }}
X-PASS: {{ password }}
X-TOPIC: {{ topic }}

{
	"args": [
		["disk_1", 82],
		["disk_2", 90]
	]
}